return {}
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = function(_, opts)
--       local mason_registry = require("mason-registry")
--       local vue_language_server_path = mason_registry.get_package("vue-language-server"):get_install_path()
--         .. "/node_modules/@vue/language-server"
--
--       -- TypeScript Language Server (ts_ls)
--       require("lspconfig").ts_ls.setup({
--         init_options = {
--           plugins = {
--             {
--               name = "@vue/typescript-plugin",
--               location = vue_language_server_path,
--               languages = { "vue" },
--             },
--           },
--         },
--       })
--
--       -- Vue Language Server (volar)
--       require("lspconfig").volar.setup({
--         init_options = {
--           vue = {
--             hybridMode = false,
--           },
--         },
--       })
--     end,
--   },
-- }
